### ISSUE TITLE
Batch export on ma

### ISSUE THREAD

**Issue by michelemangen** [StefanTraistaru/batch-export#17]
Hello,
I work on mac and have tried Batch export. I am not an expert at all but this export feature would really speed up my work... So Batch export runs but the files are not visible in Finder. In Inkscape > Open File they are however visible but open in Inkscape (which is not  the idea of exporting .png files...) Is there any mistake I made? Thank you!

**Comment by StefanTraistaru** [comment]
Hi,

Well I do not officially support MacOS. Apple does not allow me to virtualize their operating system and I don't own any MacOS devices.

That being said, we may be able to make it work, but I will need a few more details from your side:
1. What version of MacOS do you use?
2. What version of Inkscape do you use?
3. Can you please descripe in details how you have used the extension? (ex. Clicked on this, then selected this etc.)
4. Can you use the extension with the logging option enabled and upload the log file so I can have a look at it?
    - Go to the Help Tab
    - Tick the option "use logging"
    - Select a path for the log file
    - Use the extension as you tried before

You can take a look at the log file yourself too, maybe you can find a clue at what is happening. But I would appreciate if you upload it here as well.

You can use the test file from this repository to test this. It is located in the test folder.

**Comment by michelemangen** [comment]
Hello,

Thank you for your reply. I found a solution by coincidence. When I restarted the computer everything was there. 
I know that's not how it should be. And next time I use the batch export I will give you a feedback about the information you need! But for now I'm quite happy with the result ;-)

**Comment by StefanTraistaru** [comment]
I see. I'm glad you managed to make it work. If you do have the time, please update this issue so I can look into it. I would like to be able to say that the extension supports MacOS as well.

I will close this issue for now.
