### ISSUE TITLE
Recognise the background colour set in document properties.

### ISSUE THREAD

**Issue by DanielJMaxwell** [StefanTraistaru/batch-export#5]
It would be really good to have this plug-in recognise the background colour and opacity set in document properties.

Currently all exports have a transparent background unless you use a fixed layer. This adds an extra layer of work which seems a bit unnecessary given that the background colour setting already exists in the file.

When you export a png from inkscape using the command line, the default is for the background to be as set in the document properties - so I'm not sure why this is not happening in the extension. Are the document properties being deleted at some point?

I had a quick look through the code but don't know the API well enough to understand where it's going wrong.

**Comment by StefanTraistaru** [comment]
> Currently all exports have a transparent background unless you use a fixed layer. This adds an extra layer of work which seems a bit unnecessary given that the background colour setting already exists in the file.

The fixed layer feature is built with a much broader purpose, like a custom design as background that can even span multiple layers. But I agree with you, it may seem like an extra step if the result you are after is only to set a background color.

> When you export a png from inkscape using the command line, the default is for the background to be as set in the document properties - so I'm not sure why this is not happening in the extension.

When using the "Export PNG Image" function in Inkscape (GUI), the document background is visible in the output file.

But I can't actually replicate this behavior using the command line. Everything I tried completely ignores the background color set in document properties.
I have tried the following commands, where test.svg is the original Inkscape file that I'm trying to export (the extension uses the the 4th one.):

```
1. inkscape --export-type=png test.svg
2. inkscape --export-filename=output.png test.svg 
3. inkscape --export-area-page --export-filename=output.png test.svg
4. inkscape --vacuum-defs --export-area-page --export-filename=output.png test.svg
```
Can you tell me which command have you used?
If you actually used one of the commands above, can you tell me how are you using Inkscape (OS and where did you install it from)?

> Are the document properties being deleted at some point?

Not by me specifically. The extension basically:
1. Copies the current document that is opened in Inkscape;
2. Removes the unwanted layers (the layer that you want to export and background layers, if any) in that copy;
3. Uses an inkscape command (similar to the ones I wrote above) to export the newly created document in the expected file format.

If there is any data deleted from the document, other than entire layers (which should not contain any data regarding the entire document), is at step 3 and it is done by Inkscape itself.

**Comment by DanielJMaxwell** [comment]
I think I've found the issue. I am able to get the background to appear only by using the switch `--export-background-opacity="1.0"`.

It looks like a bug in Inkscape, but it would be possible to work around it by reading the `inkscape:pageopacity` property from the file and adding the value to the `export-background-opacity` switch.

**Comment by DanielJMaxwell** [comment]
Wow, what timing. Yes, I have upgraded and can confirm it now works as expected for me too. Thanks for looking into it.
